var unusedwords=[];unusedwords["the"]=1;unusedwords["a"]=1;var Site={init:function(){Site.addConsole();Site.ajax_setup();Site.init_album_loading_click();Site.initialize_facebook();Site.init_typein_quiz();Site.share_listener();Site.common_listeners();Site.scroll_listener();Site.lang_chooser_listener();},fbInitPermissions:false,fbPermissions:null,fbInitSuccess:false,fbLoginStatusRepsonse:null,quiz_cnt:0,quiz_click:false,quiz_data:null,addConsole:function(){if(!(window.console&&console.log)){window.console={log:function(){},debug:function(){},info:function(){},warn:function(){},error:function(){}};}},ajax_setup:function(){$.ajaxSetup({cache:true});$(document).ajaxSend(function(event,xhr,settings){function getCookie(name){var cookieValue=null;if(document.cookie&&document.cookie!=''){var cookies=document.cookie.split(';');for(var i=0;i<cookies.length;i++){var cookie=jQuery.trim(cookies[i]);if(cookie.substring(0,name.length+ 1)==(name+'=')){cookieValue=decodeURIComponent(cookie.substring(name.length+ 1));break;}}}
return cookieValue;}
function sameOrigin(url){var host=document.location.host;var protocol=document.location.protocol;var sr_origin='//'+ host;var origin=protocol+ sr_origin;return(url==origin||url.slice(0,origin.length+ 1)==origin+'/')||(url==sr_origin||url.slice(0,sr_origin.length+ 1)==sr_origin+'/')||!(/^(\/\/|http:|https:).*/.test(url));}
function safeMethod(method){return(/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));}
if(!safeMethod(settings.type)&&sameOrigin(settings.url)){xhr.setRequestHeader("X-CSRFToken",getCookie('csrftoken'));}});},renderXfbml:function(){FB.XFBML.parse();},check_for_permission:function(permissions,given_callback,missing_callback){FB.api('/me/permissions',function(response_perm){var perms=response_perm.data;var permission_arr=permissions.split(",");var permitted_list=[];for(var fbperm in perms){if(perms[fbperm].status=='granted'){permitted_list.push(perms[fbperm].permission);}}
console.log('permitted lits, ',permitted_list);console.log('wanted permissions, ',permission_arr);var missing_perm_list=[];var permissions_given=true;var granted_per=permitted_list.sort().join('');for(var pos in permission_arr){var s=(granted_per.indexOf(permission_arr[pos])===-1);if(s){permissions_given=false;missing_perm_list.push(permission_arr[pos]);}}
if(permissions_given){given_callback();return;}else{if(typeof missing_callback!=="undefined"){var lost=missing_perm_list.sort().join(',');console.log("missing permissions:"+ lost)
missing_callback(lost);}
return;}});},get_missing_permissions:function(){var permissions='email,public_profile';if(appConfig.perm){permissions=appConfig.perm;}
var perms=Site.fbPermissions;var permission_arr=permissions.split(",");var permitted_list=[];for(var fbperm in perms){if(perms[fbperm].status=='granted'){permitted_list.push(perms[fbperm].permission);}}
console.log('permitted lits, ',permitted_list);console.log('wanted permissions, ',permission_arr);var missing_perm_list=[];var permissions_given=true;var granted_per=permitted_list.sort().join('');for(var pos in permission_arr){var s=(granted_per.indexOf(permission_arr[pos])===-1);if(s){permissions_given=false;missing_perm_list.push(permission_arr[pos]);}}
if(permissions_given){return"";}else{var missing_permissions=missing_perm_list.sort().join(',');console.log("missing permissions:"+ missing_permissions)
return missing_permissions;}},get_all_permissions:function(){FB.api('/me/permissions',function(response_perm){var perms=response_perm.data;Site.fbPermissions=response_perm.data;Site.fbInitPermissions=true;});},initialize_facebook:function(){$('.login-btn').show()
$('.logout-btn').hide()
if($(".facebookMessenger").length>0){$(".facebookMessenger").unbind('click').on('click',function(){if(typeof FB!="undefined"){Site.openMessager();}});}
if($("#confirmok").length>0){$('#confirmok').unbind('click').on('click',function(){$("#myModal").modal("hide")
var perm='email,public_profile';if(appConfig.perm){perm=appConfig.perm;}
if(Site.fbLoginStatusRepsonse.status=='connected'){var missing_permissions=Site.get_missing_permissions();if(missing_permissions==""){Site.animate_body();Site.play_soulmate_quiz();}else{FB.login(function(response){Site.fbLoginStatusRepsonse=response;if(response.status=='connected'){Site.check_for_permission(perm,function(){Site.animate_body();Site.play_soulmate_quiz();},function(missing_permissions){console.log("denied");Site.quiz_cnt++;$("#myModal").modal("show")});}else{Site.quiz_cnt++;}},{auth_type:"rerequest",scope:missing_permissions});}}else if(Site.fbLoginStatusRepsonse.status=='unknown'){console.log("unknown logged in");Site.redirect_to_allauth_login('basic');}else{FB.login(function(response){Site.fbLoginStatusRepsonse=response;if(response.status=='connected'){Site.check_for_permission(perm,function(){Site.animate_body();Site.play_soulmate_quiz();},function(missing_permissions){console.log("denied");Site.quiz_cnt++;$("#myModal").modal("show")});}else{Site.quiz_cnt++;}},{scope:perm});}});}
window.fbAsyncInit=function(){FB.init({appId:appConfig.appId,status:true,xfbml:true,version:'v2.11',cookie:true,logging:false});$('.login-btn').unbind('click').on('click',function(){if(Site.fbInitSuccess){if(Site.fbLoginStatusRepsonse&&Site.fbLoginStatusRepsonse.status=='connected'){FB.api("me/picture?width=40&height=40",function(response){try{if(response&&response.data){$('.logout-btn').find("a").html('<img src="'+ response.data.url+'">&nbsp;&nbsp;Log-out')
$('.login-btn').hide()
$('.logout-btn').show()}}catch(err){}});}else{FB.login(function(response){Site.fbLoginStatusRepsonse=response;if(response.status=='connected'){meow_setCookie("loginstats","1")}});}}});$('.logout-btn').unbind('click').on('click',function(){meow_setCookie("loginstats","0")
$('.login-btn').show()
$('.logout-btn').hide()});FB.Event.subscribe('auth.authResponseChange',function(res){console.log(res);if(res.status=='connected'){var checkLike=function(callback){FB.api('/me/likes/1113195622079341',function(response){console.log('aa likes-->'+ response.data);if(response&&response.data[0]){if($('.fb-like').length>0){$('.fb-like-testpage').hide();$('.fb-like-newtestpage').hide();$('.fb-like-resultpage').hide();$('.fb-like-otherpage').hide();$('#analyze1').show();}
$('.like-button').hide();$('.like-button-testpage').hide();$('.like-button-newtestpage').hide();$('.like-button-resultpage').hide();$('.like-button-otherpage').hide();$('#analyze1').show();}else{if($('.fb-like').length>0){$('.fb-like').show();}
$('.like-button').show();$('.like-button-testpage').hide();$('.like-button-newtestpage').hide();$('.like-button-resultpage').hide();$('.like-button-otherpage').show();}
callback();});};var getPicture=function(callback){var s=meow_getCookie("loginstats");if(s==="1"){FB.api("me/picture?width=40&height=40",function(response){try{if(response&&response.data){$('.logout-btn').find("a").html('<img src="'+ response.data.url+'">&nbsp;&nbsp;Log-out')
$('.login-btn').hide()
$('.logout-btn').show()}}catch(err){}
callback();});}else{callback();}}
checkLike(function(){getPicture(function(){});});};});FB.Event.subscribe('edge.create',function(url,html_element){console.log("edge.create");if($('.fb-like').length>0){$('.fb-like').hide();$('#analyze1').show();}
$('.like-button').hide();$('.like-button-testpage').hide();$('.like-button-newtestpage').hide();$('.like-button-resultpage').hide();$('.like-button-otherpage').hide();$('#analyze1').show();if(appConfig&&appConfig.calculate_url){if(appConfig.calculate_url.indexOf("?")==-1){appConfig.calculate_url=appConfig.calculate_url+"?x=1";}else{appConfig.calculate_url=appConfig.calculate_url+"&x=1";}}});FB.getLoginStatus(function(response){Site.fbLoginStatusRepsonse=response;Site.fbInitSuccess=true;if(response.status=='connected'){Site.get_all_permissions();}else{console.log('logged out in fb or app not authorized, you should be redirected to facebook login if you click the button now');}});Site.init_facebook_quiz();FB.Event.subscribe('edge.create',function(href,widget){console.log("edge.create");$('.btn-nofan').toggleClass('btn-fan');});};if(typeof FB!="undefined"){window.fbAsyncInit();}(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://connect.facebook.net/"+ appConfig.fb_lang+"/sdk.js#xfbml=1&version=v2.11";fjs.parentNode.insertBefore(js,fjs);}(document,'script','facebook-jssdk'));},get_facebook_data:function(uids,callback,error_callback){var data=[];for(i in uids){data.push({method:'GET',relative_url:uids[i]+'?fields=id,name,first_name,last_name,gender,birthday,age_range,email,photos,picture'});data.push({method:'GET',relative_url:uids[i]+'/picture?height=500&width=500&return_ssl_resources=0&type=large&redirect=false'});}
FB.api('/','post',{batch:data.slice(0,50)},function(response){if(!response||response.error||response=="error"){if(typeof error_callback!=="undefined"){error_callback();}}else{console.log('RESPONSE VON / POST: ',response);var better_response=[];for(var i=0;i<response.length;i++){if(i%2){try{var data=$.parseJSON(response[i- 1].body);if(data.error||data=="error"){continue;}
data.fb_imgurl=$.parseJSON(response[i].body).data.url;}catch(err){if(typeof error_callback!=="undefined"){error_callback();}}
better_response.push(data);}}
console.log('result of request data: ',better_response);for(var m in better_response){console.log('batch response objs: ',better_response[m]);console.log(better_response[m].fb_imgurl);}
callback(better_response);}});},check_inputs:function(){if(appConfig.oid==1||appConfig.oid==2){if($('.my-quiz-result').length>0){var answer=$('.my-quiz-result').attr('eid');appConfig.loginURL_basicperms+='&ans='+ encodeURIComponent(answer);appConfig.loginURL_postperms+='&ans='+ encodeURIComponent(answer);appConfig.next_url+='&ans='+ encodeURIComponent(answer);}
return true;}
if($('#name_id').length>0){var show_error=function(target){if(target=='name'){$('.please_input_n').addClass('errorborder');$('.please_input_n').effect("shake",{times:2},1000);}
if(target=='birthday'){$('.please_input_bd').addClass('errorborder');$('.please_input_bd').effect("shake",{times:2},1000);}};var hide_error=function(target){if(target=='name'){$('.please_input_n').removeClass('errorborder');}
if(target=='birthday'){$('.please_input_bd').removeClass('errorborder');}};var validate_namequiz_inputs=function(){if($('#name_id').length>0){if(!Site.get_data_from_node('#name_id')){show_error('name');return false;}
hide_error('name');return true;}
return false;};if(!validate_namequiz_inputs()){return false;}
var answer=Site.get_data_from_node('#name_id');appConfig.loginURL_basicperms+='&ans='+ encodeURIComponent(answer);appConfig.loginURL_postperms+='&ans='+ encodeURIComponent(answer);appConfig.next_url+='&ans='+ encodeURIComponent(answer);return true;}
return true;},redirect_to_allauth_login:function(perms){console.log("redirect_to_allauth_login");if(Site.check_inputs()){var perm='email,public_profile';if(appConfig.perm){perm=appConfig.perm;}
console.log("perm "+ perm);if(perms=='basic'){var rediectURL='https://www.facebook.com/dialog/oauth?scope=';rediectURL+=encodeURIComponent(perm);rediectURL+='&redirect_uri=';rediectURL+=encodeURIComponent(appConfig.next_url);rediectURL+='&response_type=code&client_id=';rediectURL+=appConfig.appId;window.location.replace(rediectURL);}else if(perms=='posts'){var rediectURL='https://www.facebook.com/dialog/oauth?auth_type=rerequest&scope=';rediectURL+=encodeURIComponent(perm);rediectURL+='&redirect_uri=';rediectURL+=encodeURIComponent(appConfig.next_url);rediectURL+='&response_type=code&client_id=';rediectURL+=appConfig.appId;window.location.replace(rediectURL);}}},anim_timeout:3000,anim_end_time:0,reset_anim_end_time:function(){Site.anim_end_time=new Date().getTime()+ Site.anim_timeout;},expried_time:function(){return Site.anim_end_time- new Date().getTime();},update_tries:3,update_shared_url:function(share_url,success){var times=Site.expried_time();if(times<=0){success(share_url);}else{setTimeout(function(){success(share_url);},times);}},calculate:function(me,answer,res_id,soulmates,before,success,failure){var retry=appConfig.retry||0;if($('#name_id').length>0){answer=Site.get_data_from_node('#name_id');}
if($('.my-quiz-result').length>0)answer=$('.my-quiz-result').attr('eid');data={'retry':retry,'me':me,'answer':answer,'resid':res_id,'soulmates':soulmates};$.ajax({url:appConfig.calculate_url,type:'post',beforeSend:function(){before();},data:{'game':JSON.stringify(data)},dataType:"json",}).done(function(ans){if(ans.code==4000){Site.update_tries=3;success(ans.result);}else{failure();}}).fail(function(jqXHR,textStatus,error){failure(error);});},get_large_picture:function(uid,callback){FB.api(uid+"/picture?height=500&width=500&return_ssl_resources=0&redirect=false",function(response){try{console.log(uid+"/picture",response);if(response&&response.data){callback(response.data.url);return;}}catch(err){}
callback();});},play_soulmate_quiz:function(quiz_shared_callback){Site.reset_anim_end_time();if(!Site.check_inputs())return;var candidates=[];var user_numbers={post_numbers:0,like_numbers:0,friend_numbers:0};var mesignificant_other_id="";var mefamily_ids=[];var mebasic=[];var mephotoinfos=[];var mephotos=[];var mepages=[];var allwords=[];var filter_words=function(str){str=str.toLowerCase();var array=str.match(/[a-z\-']+/gi);for(var i=0;i<array.length;i++){var key=array[i];if(!unusedwords[key]){!allwords[key]?allwords[key]=1:allwords[key]++;}}};var get_hotwords=function(){var hotwords=[];var nums=[];for(var k in allwords){nums.push({word:k,num:allwords[k]});}
nums.sort(function(a,b){return b["num"]- a["num"];});for(i=0;i<10&&i<nums.length;i++){hotwords.push(nums[i]);}
return hotwords;};var gather_candidates=function(id,chance){if(candidates[id]){candidates[id]['chance']+=chance;}else{var new_candidate={id:id,chance:chance};candidates[id]=new_candidate;}};var analyze_photos=function(callback){if(appConfig.perm&&appConfig.perm.indexOf('user_photos')==-1){callback();return;}
FB.api("/me/photos?fields=picture,id&type=uploaded&return_ssl_resources=0",{limit:20},function(response){try{if(response&&response.data){console.log("/me/photos",response);for(var img in response.data){var photo=response.data[img];mephotos.push(photo.picture);mephotoinfos.push({id:photo.id,url:photo.picture});}
console.log('candidates /me/photos',candidates);}}catch(err){}
callback();});};var get_likes=function(get_likes_step,get_likes_nextid,callback){if(appConfig.perm&&appConfig.perm.indexOf('user_likes')==-1){callback();return;}
var bakurl="/me/likes?since=1420070400&limit=100";if(typeof get_likes_nextid!='undefined'&&get_likes_nextid!=''){bakurl="/me/likes?since=1420070400&limit=100&after="+ get_likes_nextid;}
FB.api(bakurl,function(response){try{if(response&&response.paging&&response.data&&response.data.length>0){user_numbers.like_numbers+=response.data.length;for(var f in response.data){if(mepages.length>=20)break;var page=response.data[f];mepages.push(page);}
if(response.paging.next&&response.paging.cursors&&response.paging.cursors.after){get_likes_nextid=response.paging.cursors.after;}}}catch(err){}
callback(get_likes_step- 1,get_likes_nextid,callback);});};var analyze_likes=function(callback){get_likes(5,'',function(get_likes_step,get_likes_nextid,myback){if(get_likes_nextid!=''&&get_likes_step>0){get_likes(get_likes_step,get_likes_nextid,myback);}else{callback();}});};var analyze_friends=function(callback){if(appConfig.perm&&appConfig.perm.indexOf('user_friends')==-1){callback();return;}
FB.api("/me/friends",function(response){try{if(response&&response.data&&response.data.length>0){user_numbers.friend_numbers=response.data.length;for(var f in response.data){gather_candidates(response.data[f].id,1);}}}catch(err){}
callback();});};var analyze_family=function(callback){if(appConfig.perm&&appConfig.perm.indexOf('user_relationships')==-1){callback();return;}
FB.api("/me/family",function(response){try{if(response&&response.data&&response.data.length>0){for(var f in response.data){gather_candidates(response.data[f].id,1);mefamily_ids[response.data[f].id]=1;}}}catch(err){}
callback();});};var analyze_me_significant_other=function(callback){if(appConfig.perm&&appConfig.perm.indexOf('user_relationships')==-1){callback();return;}
FB.api('/me?fields=significant_other',function(response){try{console.log("analyze_me_significant_other-->",response);if(response&&response.significant_other&&response.significant_other.id){mesignificant_other_id=response.significant_other.id;gather_candidates(mesignificant_other_id,1);}}catch(err){}
callback();});};var analyze_posts=function(callback){if(appConfig.perm&&appConfig.perm.indexOf('user_posts')==-1){candidates=Object.keys(candidates).sort(function(a,b){return candidates[b]['chance']- candidates[a]['chance'];});callback(candidates);return;}
FB.api('/me/posts?fields=message&since=1420070400&limit=100',function(response){try{if(response&&response.data&&response.data.length>0){user_numbers.post_numbers=response.data.length;for(var stat in response.data){var interaction=response.data[stat];if(interaction.message){filter_words(interaction.message);}}}}catch(err){}
candidates=Object.keys(candidates).sort(function(a,b){return candidates[b]['chance']- candidates[a]['chance'];});callback(candidates);});};var ts=new Date().getTime()+ 5000;var get_user_and_soulmate_data=function(soulmates){Site.get_facebook_data(['me'],function(response){var me=response[0];console.log(soulmates);Site.get_facebook_data(soulmates,function(response){console.log('soulmates-->'+ soulmates);console.log(response);var mefamily=[];var mesignificant_other=null;var final_candidates=[];for(sm in response){console.log('response sm,',response[sm]);console.log('candidate name: ',response[sm].first_name);if(response[sm].id!=me.id){if(mesignificant_other_id==response[sm].id){mesignificant_other=response[sm];}else if(mefamily_ids[response[sm].id]){mefamily.push(response[sm]);}else{final_candidates.push(response[sm]);}}}
console.log('start playing soulmate quiz.. ');console.log('user_image:'+ me.fb_imgurl);console.log(me);console.log('final_candidates-->'+ final_candidates);me.like_numbers=user_numbers.like_numbers;me.post_numbers=user_numbers.post_numbers;me.friend_numbers=user_numbers.friend_numbers;me.photos=mephotos;me.pages=mepages;me.family=mefamily;me.significant_other=mesignificant_other;me.hotwords=get_hotwords();var res_id=Site.select_proper_gender_result(me.gender);var cachefbstr={'me':me,'candidates':final_candidates,};if(appConfig.oid&&(appConfig.oid==3||appConfig.oid==4)){if(appConfig.show_photos_picker&&appConfig.show_photos_picker==1){$(".image-item").remove();Site.quiz_data={};Site.quiz_data.me=me;Site.quiz_data.res_id=res_id;Site.quiz_data.final_candidates=final_candidates;var item='<div class="meow-custom-xs-4 meow-custom-sm-3 padding-spa-15 a-ac image-item" ><div class="photo-item a-ac" frm="me" data="'+ me.fb_imgurl+'" style="background: url('+ me.fb_imgurl+') center center; background-size:cover;"></div></div>';$(".photo-album").append(item);for(i=0;i<8&&i<mephotoinfos.length;i++){var item='<div class="meow-custom-xs-4 meow-custom-sm-3 padding-spa-15 a-ac image-item" ><div class="photo-item a-ac" frm="'+ mephotoinfos[i].id+'" data="'+ mephotoinfos[i].url+'" style="background: url('+ mephotoinfos[i].url+') center center; background-size:cover;"></div></div>';$(".photo-album").append(item);}
Site.init_album_loading_click();ts=ts- new Date().getTime();var winTimer=window.setInterval(function(){console.log("dd");Site.swap_to_selected_pic();window.clearInterval(winTimer);},ts);return;}else{me.def_image_url=me.fb_imgurl;}}
Site.calculate(me,'',res_id,final_candidates,function(){Site.switch_calculation_animations();},function(succ_msg){Site.update_shared_url(succ_msg.url,function(url){if(typeof quiz_shared_callback=='undefined'){Site.redirect_to_result(url);}else{quiz_shared_callback(url);}});},function(error){Site.deanimate_body();});});});};var post_datas=function(){Site.calculate([],'',0,[],function(){},function(succ_msg){Site.update_shared_url(succ_msg.url,function(url){if(typeof quiz_shared_callback=='undefined'){Site.redirect_to_result(url);}else{quiz_shared_callback(url);}});},function(error){});};if(typeof quiz_shared_callback=='function'){post_datas();return;}
analyze_photos(function(){analyze_likes(function(){analyze_family(function(){analyze_friends(function(){analyze_me_significant_other(function(){analyze_posts(function(soulmates){console.log(soulmates);meow_setCookie("loginstats","1")
get_user_and_soulmate_data(soulmates);});});});});});});},checkFbInitTimer:null,quiz_click_end:function(){Site.quiz_click=false;$('.fb_quiz_click').removeAttr("disabled");},playCallback:function(){if(Site.quiz_cnt>0){$("#myModal").modal("show")
return}
if(Site.fbInitSuccess){if(Site.fbLoginStatusRepsonse.status=='connected'){if(!Site.fbInitPermissions){return;}}}else{return;}
if(Site.quiz_click)return;$('.fb_quiz_click').attr("disabled",true);Site.quiz_click=true;Site.deanimate_body();var perm='email,public_profile';if(appConfig.perm){perm=appConfig.perm;}
if(Site.fbLoginStatusRepsonse.status=='connected'){var missing_permissions=Site.get_missing_permissions();if(missing_permissions==""){Site.animate_body();Site.play_soulmate_quiz();Site.quiz_click_end();}else{Site.deanimate_body();console.log('permission not given, asking to permit....');FB.login(function(response){Site.fbLoginStatusRepsonse=response;if(response.status=='connected'){Site.check_for_permission(perm,function(){Site.animate_body();Site.play_soulmate_quiz();Site.quiz_click_end();},function(missing_permissions){console.log("denied");Site.quiz_cnt++;Site.quiz_click_end();$("#myModal").modal("show")});}else{Site.quiz_click_end();Site.quiz_cnt++;}},{auth_type:"rerequest",scope:missing_permissions});}}else if(Site.fbLoginStatusRepsonse.status=='unknown'){Site.redirect_to_allauth_login('basic');Site.quiz_click_end();}else{FB.login(function(response){Site.fbLoginStatusRepsonse=response;if(response.status=='connected'){Site.check_for_permission(perm,function(){Site.animate_body();Site.play_soulmate_quiz();Site.quiz_click=false;$('.fb_quiz_click').removeAttr("disabled");},function(missing_permissions){console.log("denied");Site.quiz_cnt++;Site.quiz_click_end();$("#myModal").modal("show")});}else{Site.quiz_cnt++;Site.quiz_click_end();}},{scope:perm});}},init_facebook_quiz:function(){if($('.fb_quiz_click').length>0){if(appConfig.start_quiz){console.log('init fb_quiz_click is 222');Site.animate_body();Site.initFBTimer=setInterval(function(){if(Site.fbInitSuccess){if(Site.fbLoginStatusRepsonse.status=='connected'){if(!Site.fbInitPermissions){return;}}}else{return;}
window.clearInterval(Site.initFBTimer);if(Site.fbLoginStatusRepsonse.status=='connected'){var missing_permissions=Site.get_missing_permissions();if(missing_permissions==""){Site.play_soulmate_quiz();}else{Site.deanimate_body();console.log("ok fb init get_missing_permissions",missing_permissions)
$('.fb_quiz_click').unbind('click').on('click',function(){Site.playCallback()});}}else if(Site.fbLoginStatusRepsonse.status=='unknown'){Site.deanimate_body();console.log('11 unknown logged out in fb or app not authorized, you should be redirected to facebook login if you click the button now');$('.fb_quiz_click').unbind('click').on('click',function(){Site.redirect_to_allauth_login('basic');});}else{Site.deanimate_body();console.log('logged out in fb or app not authorized, you should be redirected to facebook login if you click the button now');$('.fb_quiz_click').unbind('click').on('click',function(){Site.playCallback()});}},1000);}else{console.log('init fb_quiz_click is 111');$('.fb_quiz_click').unbind('click').on('click',function(){console.log('first click is here');Site.playCallback()});}}},init_typein_quiz:function(){if($('.typein_quiz_click').length>0){$('.typein_quiz_click').unbind('click').on('click',function(){Site.play_typein_quiz();});$('input[name=answer]').keypress(function(e){if(e.which==13){Site.play_typein_quiz();}});}},playWidthImage:function(_imgurl){Site.animate_body(2);var imgurl=_imgurl;console.log("imgurl->"+ imgurl);$.ajax({url:"/face/api/checkface.php",type:"POST",dataType:'JSON',data:{img1:imgurl},success:function(data){if(data&&data.code==4000){Site.quiz_data.me.def_image_url=imgurl;Site.calculate(Site.quiz_data.me,'',Site.quiz_data.res_id,Site.quiz_data.final_candidates,function(){$('#picholder').hide();Site.animate_body(1);Site.switch_calculation_animations(1);},function(succ_msg){Site.update_shared_url(succ_msg.url,function(url){Site.redirect_to_result(url);});},function(error){Site.deanimate_body(1);$('#picholder').show();});}else{Site.deanimate_body(2);Site.swap_to_selected_pic();$("#uploadTips").find(".modal-body").html("<h4> No face on the image or the image is too small, please choose another one.</h4>")
$("#uploadTips").modal("show");}},error:function(data){Site.deanimate_body(2);Site.swap_to_selected_pic();$("#uploadTips").find(".modal-body").html("<h4> No face on the image or the image is too small, please choose another one.</h4>")
$("#uploadTips").modal("show");}});},init_album_loading_click:function(){$(".upload-file").unbind("change").on("change",function(){var explorer=navigator.userAgent;var imgSrc=$(this)[0].value;if(explorer.indexOf('MSIE')>=0){}else{imgSrc=$(this)[0].files[0];}
if(imgSrc==""){console.log("error upload");$("#uploadTips").find(".modal-body").html("<h4> Unknown error on the chosen image, please choose another one.</h4>")
$("#uploadTips").modal("show");}else{var filename=$(this).val();if(!/\.(jpg|jpeg|png|JPG|PNG|JPEG)$/.test(filename)){console.log("upload file is not a image.");$("#uploadTips").find(".modal-body").html("<h4> Only image files can be uploaded.</h4>")
$("#uploadTips").modal("show");return;}
Site.animate_body(2);var fd=new FormData();fd.append("Filedata",imgSrc);$.ajax({url:"/test/tpl/upload.php",type:"POST",dataType:'JSON',processData:false,contentType:false,data:fd,success:function(data){console.log("success-->"+ JSON.stringify(data));if(data&&data.code==4000){Site.playWidthImage(data.result);}else{Site.deanimate_body(2);Site.swap_to_selected_pic();$("#uploadTips").find(".modal-body").html("<h4> Failed uploading image, could be bad internet connection, please try again or choose another image.</h4>")
$("#uploadTips").modal("show");}},error:function(data){console.log("error-->"+ JSON.stringify(data));Site.deanimate_body(2);Site.swap_to_selected_pic();console.log("error upload ee");$("#uploadTips").find(".modal-body").html("<h4> Failed uploading image, could be bad internet connection, please try again or choose another image.</h4>")
$("#uploadTips").modal("show");}});}
return false;});$('.upload-image-button').unbind("click").on('click',function(){$(".upload-file").val('');$(".upload-file").click();});$(".photo-item").unbind("click").on('click',function(){var meimgurl=$(this).attr("data");Site.get_large_picture($(this).attr("frm"),function(url){if(typeof url=="undefined"){console.log("use raw imgurl="+ meimgurl);Site.playWidthImage(meimgurl);}else{console.log("use new imgurl="+ url);Site.playWidthImage(url);}});});},play_typein_quiz:function(){var show_error=function(target){if(target=='name'){$('.please_input_n').addClass('errorborder');$('.please_input_n').effect("shake",{times:2},1000);}
if(target=='birthday'){$('.please_input_bd').addClass('errorborder');$('.please_input_bd').effect("shake",{times:2},1000);}};var hide_error=function(target){if(target=='name'){$('.please_input_n').removeClass('errorborder');}
if(target=='birthday'){$('.please_input_bd').removeClass('errorborder');}};var validate_birthday=function(birthday){if(appConfig.perm&&appConfig.perm.indexOf('user_birthday')==-1){callback();return;}
var year=birthday.split('-')[0];if(year.length>4||+year<=1900){return false;}
return true;};var validate_namequiz_inputs=function(){if($('#birthday_id').length>0){if(!validate_birthday(Site.get_data_from_node('#birthday_id'))){show_error('birthday');console.log('birthday error');return false;}
hide_error('birthday');return true;}else if($('#name_id').length>0){if(!Site.get_data_from_node('#name_id')){show_error('name');console.log('name error');return false;}
hide_error('name');return true;}
return false;};if(!validate_namequiz_inputs()){console.log('validation didnot pass, deanimating the body again');return;}
console.log('validation passed');var res_id=0;var answer=Site.get_data_from_node('#name_id');var birthday=Site.get_data_from_node('#birthday_id');Site.animate_body();if(birthday!==""){var me={'birthday':birthday};}else{var me={};}
Site.calculate(me,answer,res_id,[],function(){console.log('switching calculation steps');Site.switch_calculation_animations();},function(ans){Site.update_shared_url(ans.url,function(url){Site.redirect_to_result(url);});},function(error){Site.deanimate_body();});},shared_clicked:function(){$.ajax({url:appConfig.shared_click_url,type:'get',data:{'id':appConfig.id,'t':new Date().getTime()},dataType:"json",}).done(function(ans){}).fail(function(jqXHR,textStatus,error){});},test_clicked:function(){$.ajax({url:appConfig.click_url,type:'get',data:{'id':appConfig.id,'t':new Date().getTime()},dataType:"json",}).done(function(ans){}).fail(function(jqXHR,textStatus,error){});},openMessager:function(){var shareurl=$('.share_in_fb_click').data('sharelink');var u=navigator.userAgent,app=navigator.appVersion;var isAndroid=u.indexOf('Android')>-1||u.indexOf('Linux')>-1;var isiOS=!!u.match(/\(i[^;]+;( U;)? CPU.+Mac OS X/);var goPage=function(t){window.location.href=t;};try{if(isiOS){goPage("fb-messenger-share://?type=FBShareableTypeURL&link="+ encodeURIComponent(shareurl));}else if(isAndroid){goPage("intent://share/#Intent;scheme=fb-messenger;package=com.facebook.orca;S.android.intent.extra.TEXT="+ encodeURIComponent(shareurl)+";end");}else{FB.ui({method:'send',link:shareurl,display:'popup'},function(response){});}}catch(e){console.log("e",e)}},newwindow:null,openShareDialog:function(){var ua=navigator.userAgent;Site.shared_clicked();var left=(screen.availWidth- 572)/ 2;var top=(screen.availHeight- 567)/ 2;var shareurl=$('.share_in_fb_click').data('sharelink');var videourl=$('.share_in_fb_click').data('videolink');var sharepicture=$('.img-responsive').data('sharepicture');Site.update_tries=3;Site.update_shared_url(shareurl,function(url){});var newurl='https://m.facebook.com/sharer/sharer.php?u='+ encodeURIComponent(shareurl)+'&picture='+ sharepicture+'&app_id='+ appConfig.appId;var newurl_2='https://www.facebook.com/v2.9/dialog/share?app_id='+ appConfig.appId+'&display=popup&href='+ encodeURIComponent(shareurl)+'&mobile_iframe=false&picture='+ encodeURIComponent(sharepicture)+'&sdk=joey&version=v2.9';var uadetect=navigator.userAgent||navigator.vendor||window.opera;if(uadetect&&(uadetect.indexOf("iPhone")!=-1||uadetect.indexOf("iphone")!=-1||uadetect.indexOf("IOS")!=-1||uadetect.indexOf("ios")!=-1))
{if(appConfig.oid&&appConfig.oid==4){FB.ui({method:'feed',redirect_uri:appConfig.forward_link,link:shareurl,picture:sharepicture,hashtag:'#meowshare',mobile_iframe:false},function(response){console.log('share result-->'+ response);window.location.href=appConfig.forward_link;});}else{FB.ui({method:'feed',display:"popup",link:shareurl,picture:sharepicture,mobile_iframe:false},function(response){console.log('share result-->'+ response);window.location.href=appConfig.forward_link;});}}else{if(appConfig.oid&&appConfig.oid==4){FB.ui({method:'share',redirect_uri:appConfig.forward_link,href:shareurl,hashtag:'#meowshare',picture:sharepicture,mobile_iframe:false},function(response){console.log('share result-->'+ response);window.location.href=appConfig.forward_link;});}else{Site.newwindow=window.open(newurl,'facebooksharer','width=572,height=567,left='+ left+",top="+ top);var winTimer=window.setInterval(function(){if(typeof Site.newwindow!=="undefined"&&Site.newwindow!==null){if(Site.newwindow.closed!==false){window.clearInterval(winTimer);window.location.href=appConfig.forward_link;}}
else{window.location=newurl;}},200);}}},share_listener:function(){$('.share_in_fb_click').unbind('click').on('click',function(){Site.openShareDialog();});$('.share_in_tw_click').unbind('click').on('click',function(){window.open('http://twitter.com/share?url='+ encodeURIComponent($(this).data('sharelink')),'twitter-share-dialog','width=572,height=467');});$('.share_in_fb_click_no_redirect').unbind('click').on('click',function(){$('.ll-share').toggleClass('hidden');$('.op-50').toggleClass('op-100');window.open('https://www.facebook.com/sharer/sharer.php?u='+ encodeURIComponent($(this).data('sharelink')),'facebook-share-dialog','width=572,height=567');});},common_listeners:function(){var slide=function(css_class){$(css_class).delay(50).show().animate({opacity:1,top:"45px"},'fast');};slide(".ll-like");if($("#divtoBlink").length){setInterval(function(){$("#divtoBlink").toggleClass("backgroundRed");},300);}
$('.ll-close').unbind('click').on('click',function(){$('.ll-like').toggleClass('hidden');$('.llayer').toggleClass('hidden');$('.ll-share').toggleClass('show-res');$('.op-50').toggleClass('op-100-res');slide(".ll-share");});$('.ll-close2').unbind('click').on('click',function(){$('.ll-share').toggleClass('hidden');$('.op-50').toggleClass('op-100');});},animate_album_loading:function(){$('.fb-comments').hide();$('.hidablead').hide();$('.smalladshow').show();$('.randgame').show();$("html, body").animate({scrollTop:0},"slow");$('.jumbotron').hide();$('#analyze1').hide();$('#analyze2').show();$('#analyze3').hide();$('#loader').show();if($('.full_loading').length>0)$('.full_loading').show();},deanimate_album_loading:function(){if($('.full_loading').length>0)$('.full_loading').hide();$('#loader').hide();$('.jumbotron').show();$('.fb-comments').show();$('.hidablead').show();$('.smalladshow').show();$('.randgame').show();},lang_chooser_listener:function(){$('#langchooser').on('change',function(){var location=window.location.href;var lang=$(this).val();if(String(location).indexOf('id')>0||String(location).indexOf('es')>0||String(location).indexOf('pt')>0||String(location).indexOf('en')>0||String(location).indexOf('fr')>0||String(location).indexOf('nl')>0||String(location).indexOf('pl')>0||String(location).indexOf('tr')>0||String(location).indexOf('ph')>0||String(location).indexOf('ml')>0||String(location).indexOf('tw')>0){window.location.replace("//"+ lang+".meow-share.com");}else{window.location.replace("//"+ lang+".analyz.me");}});},animate_body:function(flag){if(typeof flag=="undefined"&&appConfig.show_photos_picker==1&&appConfig.oid&&(appConfig.oid==3||appConfig.oid==4)){Site.animate_album_loading();return;}
if($('.full_loading').length>0)$('.full_loading').show();$('.fb-comments').hide();$('.hidablead').hide();$('.smalladshow').show();$('.randgame').show();$("html, body").animate({scrollTop:0},"slow");$('.jumbotron').hide();if(flag==2){$('#analyze1').hide();$('#analyze2').hide();$('#analyze3').show();$("#picholder").hide();}else{$('#analyze1').show();$('#analyze2').hide();$('#analyze3').hide();}
$('#loader').show();},deanimate_body:function(flag){if(typeof flag=="undefined"&&appConfig.show_photos_picker==1&&appConfig.oid&&(appConfig.oid==3||appConfig.oid==4)){Site.deanimate_album_loading();return;}
console.log('deanimating ...');if($('.full_loading').length>0)$('.full_loading').hide();$('#loader').hide();if(flag==2){$('.jumbotron').hide();}else{$('.jumbotron').show();}
$('#step1').show();$('#step2').hide();$('.fb-comments').show();$('.hidablead').show();$('.smalladshow').show();$('.randgame').show();},swap_to_selected_pic:function(){if($('.full_loading').length>0)$('.full_loading').hide();$('#loader').hide();$('#picholder').show();},switch_calculation_animations:function(flag){if(typeof flag=="undefined"&&appConfig.show_photos_picker==1&&appConfig.oid&&(appConfig.oid==3||appConfig.oid==4)){return;}
$('#step1').hide();$('#step2').show();},redirect_to_result:function(url){console.log(url);window.location.href=url;},get_data_from_node:function(selector){return $.trim($(selector).val());},get_random_result_from:function(results){return results[Math.floor(Math.random()*results.length)];},select_proper_gender_result:function(gender){var res_id=0;return res_id;},rand_game:function(callback){Site.next_page(24,function(data){if($('.randgame').length>0){$('.randgame').empty();}
var i=0;for(i=0;i<24&&i<data.length;i++){var g=data[i];var testurl=appConfig.test_basic_url+ g.id+"/";if(typeof cureva!="undefined"&&cureva!=""){testurl+="?evb="+ cureva;}
var item='<div class="meow-custom-xs-12 meow-custom-sm-4 more-quizzes padding-spa-15 a-ac"><a href="'+ testurl+'"><div class="cross-item a-ac" style="min-height:225px;"><div class="more-quizzes-cropped"><div class="item-img" style="background: url('+ g.cover_pic+') center center;background-size:cover;"></div></div><span>'+ g.title+'</span> </div></a></div>';if($('.randgame').length>0){$('.randgame').append(item);}}
if(typeof callback=="function"){callback();}});},showLoadingItem:function(){},hideLoadingItem:function(){},next_page:function(pagesize,callback){pagesize=pagesize||24;if(!Site.fetch&&appConfig.pageIndex<appConfig.totalPage){Site.fetch=true;$.ajax({url:appConfig.rand_game_url,type:'get',dataType:'json',data:{page:appConfig.pageIndex,t:Math.random(),'pagesize':pagesize},beforeSend:function(){Site.MORE_PANEL.remove();},complete:function(){Site.hideLoadingItem();Site.fetch=false;},error:function(){Site.hideLoadingItem();Site.fetch=false;}}).done(function(ans){if(ans.code==4000&&ans.result&&ans.result.list){var pageinfo=ans.result.pageinfo;appConfig.totalPage=pageinfo.totalPage;appConfig.pageIndex=pageinfo.pageIndex+ 1;appConfig.totalCount=pageinfo.totalCount;var data=ans.result.list;for(var i in data){var g=data[i];var testurl=appConfig.test_basic_url+ g.id+"/";if(typeof cureva!="undefined"&&cureva!=""){testurl+="?evb="+ cureva;}
var item='<div class="meow-custom-xs-12 meow-custom-sm-4 o-oct meow-custom-md-12 padding-spa-15 meox"><a href="'+ testurl+'"><div class="cross-item a-ac"><div class="o-oct-cropped"><div class="item-img" style="background: url('+ g.cover_pic+') center center;background-size:cover;"></div></div><span>'+ g.title+'</span> </div></a></div>';$('#lefto-oct').append(item);}
if(appConfig.pageIndex<appConfig.totalPage){$('#lefto-oct').append(Site.MORE_PANEL);}
if(typeof(callback)=="function"){callback(data);}}
Site.fetch=false;}).fail(function(jqXHR,textStatus,error){if(typeof failure=='function')failure(error);Site.fetch=false;});}},fetch:false,MORE_PANEL:$('<div class="buttons-layout loading-layout"><div class="row"><span class="drag-font"><strong>Drag Up to Show More</strong></span></div><div></div></div>'),scroll_listener:function(){$(document).unbind("scroll");$(document).bind("scroll",function(event){if($(document).scrollTop()+ $(window).height()>=$(document).height()- 50){Site.next_page();}});}}
$(function(){if(typeof cureva!="undefined"){cureva=encodeURIComponent(cureva);}
Site.init();if(appConfig.oid&&appConfig.oid==2){Site.test_clicked();}
if(appConfig.rand_game){Site.rand_game(function(){var rndGameShow=$('.randgame').is(":visible");if(rndGameShow){if($(".adsframe").length>0&&$('#lefto-oct').length>0){$('#lefto-oct').prepend($(".adsframe"));}}else{if($(".adsframe").length>0&&$('#lefto-oct').length>0){var item=$('#lefto-oct .meox:eq(2)');if(item){$(".adsframe").insertAfter(item);}else{$('#lefto-oct').append($(".adsframe"));}}}
setInterval(function(){var vbs=$('.randgame').is(":visible");if(vbs!=rndGameShow){rndGameShow=vbs;if(rndGameShow){if($(".adsframe").length>0&&$('#lefto-oct').length>0){$('#lefto-oct').prepend($(".adsframe"));}}else{if($(".adsframe").length>0&&$('#lefto-oct').length>0){var item=$('#lefto-oct .meox:eq(2)');if(item){$(".adsframe").insertAfter(item);}else{$('#lefto-oct').append($(".adsframe"));}}}}},500);});}
if(typeof addQuizItemWatch!='undefined'){addQuizItemWatch();}})
function meow_getCookie(name){var arr,reg=new RegExp("(^| )"+ name+"=([^;]*)(;|$)");if(arr=document.cookie.match(reg))return unescape(arr[2]);else
return'';}
function meow_setCookie(name,value){var Days=1;var exp=new Date();exp.setTime(exp.getTime()+ Days*24*60*60*1000);document.cookie=name+"="+ escape(value)+";expires="+ exp.toGMTString()+'; path=/';}